packages:
  - "packages/*"

allowBuilds:
  msw: set this to true or false
  protobufjs: set this to true or false

# Allow build scripts for these deps
onlyBuiltDependencies:
  - esbuild
  - msw
  - protobufjs
